---
ansible_connection: local

build:
  NAME: '{{ app_name }}'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: consultant-360-fe-bc
        template: '{{ playbook_dir }}/templates/consultant-360-fe-bc.yml'
        params: "{{ playbook_dir }}/params/consultant-360-fe-bc"
        namespace: "{{ ci_cd_namespace }}"
        tags:
        - ci-cd
      - name: consultant-360-fe-build
        template: '{{ playbook_dir }}/templates/consultant-360-fe-is.yml'
        params: "{{ playbook_dir }}/params/consultant-360-fe-is"
        namespace: "{{ dev_namespace }}"
        tags:
        - build
      - name: keycloak
        template: '{{ playbook_dir }}/templates/keycloak.yml'
        params_from_vars:
          NAME: keycloak
        namespace: "{{ dev_namespace }}"
        tags:
        - sso

