---
ansible_connection: local

build:
  NAME: '{{ app_name }}'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: survey-spring-service-cicd
        template: '{{ playbook_dir }}/templates/survey-spring-service-cicd.yml'
        params: "{{ playbook_dir }}/params/survey-spring-service-cicd"
        namespace: "{{ ci_cd_namespace }}"
        tags:
        - ci-cd
        - survey-spring-service
      - name: survey-spring-service-resources
        template: '{{ playbook_dir }}/templates/survey-spring-service-resources.yml'
        params: "{{ playbook_dir }}/params/survey-spring-service-resources"
        namespace: "{{ dev_namespace }}"
        tags:
        - build
        - survey-spring-service

